"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { useEffect, useRef, useState } from "react";
import boutonX from '../../public/cross.svg';
import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import burgerImg from '../../public/menu.svg';
import Head from "next/head";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [togel,setTogel]=useState(false)
  const [token,setToken]=useState<string>('');
  const [image,setImage]=useState(burgerImg);
  const [show,setShow]=useState(true)

    const router=useRouter();
    
    const LogOut=()=>{
      localStorage.removeItem("token");
      setToken('');
      setUser('');
      router.push(`/login?ReturnUrl=${pathname}`);
    }
    const getPath=()=>{
        return pathname.split('/').join('>').substring(1);
    }
 
 function toggleNav(){
   setImage((!togel)?boutonX:burgerImg);
   setTogel(!togel);
 }

 const [user,setUser]=useState<any>(null);
  const pathname=usePathname();
  useEffect(()=>{
    setToken(localStorage.getItem("token") as string);
    if (window.localStorage&&localStorage.getItem("token")) {
      setUser(JSON.parse(atob(localStorage.getItem("token")!.split('.')[1])));
    }
    //setUser('');
  },[image,togel,token]);

  return (
      <html lang="en">
        <Head><title>Home Page</title></Head>
        <body className="flex min-h-screen " onClick={()=>{
          if (togel) {
            setTogel(false);
            setImage(burgerImg);
          }
        }}>
          <div id="toggled-menu"
              className={`w-full absolute top-0 bottom-0 left-0 -translate-x-full md:border-r bg-gray-50  ${togel?'translate-x-0 z-20 opacity-100 w-3/4 translate-y-9':''} text-gray-800 border-b border-gray-200 flex flex-col items-center md:static md:w-min md:transform-none md:border-none`}>
            <h1 className="text-xl font-bold p-1 w-full h-12 border-b">Applications</h1>
            <div className="flex-1 flex w-full flex-col"> 
            
            {
              user?(
              <nav className="flex flex-col flex-1 py-3 space-y-6 text-justify w-full">
                  <Link href="/application" className={`px-2 text-xl ${pathname=="/application"&&'active'}`}>Application</Link>
                  <Link href="/" className={`px-2 capitalize text-xl ${pathname=="/"?'active':''}`}>{user?.username}</Link>
              </nav>
              ):(
                <nav className="flex flex-col flex-1 py-3 space-y-6 text-justify w-full">
                    <Link href="/register" className={`px-2 text-xl ${pathname=="/register"&&'active'}`}>Regiter</Link>
                    <Link href="/login" className={`px-2 text-2xl ${pathname=="/login"?'active':''}`}>Login</Link>
                </nav>
              )
            }
            </div>
            <Footer/>
            </div>
          <div className="flex-1 flex flex-col h-screen">
            <div className="flex flex-row h-12 bg-gray-50  justify-between items-center  w-full border-b">
              <button
                aria-label="toggle button"
                aria-expanded="false"
                id="menu-btn"
                className="cursor-pointer w-7 md:hidden"
                onClick={toggleNav}
                >
                  <Image src={image} alt="button"/>
              </button>
                <span className=" capitalize pl-1 invisible md:visible md:w-1/3">{getPath()}</span>
                {
                  token?<button onClick={LogOut} className="about">LogOut</button>:<Link href="/about" className="about">About</Link>
                }
            </div>
            <div className="flex-1">
              {children}
            </div>
          </div>
        </body>
      </html>
  );
}
